### ISSUE TITLE
Unable to find the plugin from the command palette

### ISSUE THREAD

**Issue by fdmarcin** [Vasily-X/AutoFoldCode#1]
Hi,

When I open the ST3 command palette and choose "Package Control: Install package" and search for your plugin, it's not there, though it's on the Package Control website.

Sublime Text build 3143 for Linux 

![autofoldcode](https://user-images.githubusercontent.com/25668969/34884940-9c31ec28-f7be-11e7-8968-00a637c2a515.png)

**Comment by ergonomicus** [comment]
@RIDE-2DAY This is the message from packagecontrol.io:

`Package info was unavailable last time crawler ran. No valid semver tags found at https://github.com/RIDE-2DAY/AutoFoldCode/tags for the package "AutoFoldCode" in the repository https://packagecontrol.io/repository.json.`

**Comment by Vasily-X** [comment]
@fdmarcin @ergonomicus hello, I'm sorry for the delay, I've just realized there was an issue here. I'm going to look into it right now.

**Comment by ergonomicus** [comment]
@RIDE-2DAY Not sure, but I think you need at least one release or tag... Maybe you could start there :)

Thanks.

**Comment by RIDE-2DAY** [comment]
@ergonomicus I've just released one version but as far as I know it doesn't require any tag. I didn't add any, I thought merging it into the `package_control_channel` would do the job. I'll let you know.

**Comment by Vasily-X** [comment]
@ergonomicus @fdmarcin it should be working now.

Kind regards.

**Comment by fdmarcin** [comment]
Works now. Good job, @RIDE-2DAY !
