### ISSUE TITLE
Wrong state is saved when a document is modified, but closed without saving

### ISSUE THREAD

**Issue by 64kramsystem** [Vasily-X/AutoFoldCode#10]
(This is related to #9)

If a document is modified, but closed without save, the wrong AFC state will be saved, causing the document to have broken folds when opened.

This is caused by AFC listening on close. As written in #9, I think this event should no be listened to - if that'd be the case, this bug wouldn't happen (but again, I'm not familiar with the ST3 event system).

**Comment by acheronfail** [comment]
As has been mentioned in #9, this is a case where AutoFoldCode has made a choice which must choose between two styles of using Sublime Text:

* Effects of saving on close:
    * users using projects and the hot exit feature will benefit from having saved and up-to-date code folds
    * users not using the above feature may see some incorrect states if they close files without re-opening them with the unmodified buffer
* Effects of _not_ saving on close:
    * precisely the opposite of the above

---

Perhaps a configuration option which can disable saving on close could solve your use-case here?

We're open to PRs in this case provided it doesn't change the plugin's default behaviour.
