### ISSUE TITLE
AutoFoldCode FAIL

### ISSUE THREAD

**Issue by MarkCate** [Vasily-X/AutoFoldCode#12]
This app is not installing in Sublime Text. App shows install during Package Control , but nothing expected installs.

**Comment by Vasily-X** [comment]
@MarkCate could you install other packages successfully via Package Control? I assume you installed Package Control wrong, please reinstall it and try again.

**Comment by acheronfail** [comment]
Closing this since we don't have enough information to successfully debug this.

If you encounter the issue feel free to re-open. :)
