### ISSUE TITLE
AutoFoldCode not working on the current ST3 version on Linux

### ISSUE THREAD

**Issue by 64kramsystem** [Vasily-X/AutoFoldCode#3]
Hello!

I've been an AutoFoldCode user for some time, however, it doesn't work anymore.

When I select and fold an area, I can see that the file `.config/sublime-text-3/Packages/User/trailing_spaces.sublime-settings` contains the folding data, however, if I close ST and reopen it again, the folding regions are not applied.

My system is an Ubuntu, and the ST build is 3164.

**Comment by acheronfail** [comment]
@saveriomiroddi hmm I'm not sure you're looking at the correct file. If you [read the source](https://github.com/RIDE-2DAY/AutoFoldCode/blob/master/AutoFoldCode.py#L7), AutoFoldCode actually stores its data in `Packages/Users/AutoFoldCode.sublime-settings`.

I've just tried it on Linux and macOS (build 3164) and it's working as expected.

~~Did you make sure to restart Sublime Text after installing it?~~ Just read that you'd already been using it for a while. Have a look and see what's in your `AutoFoldCode.sublime-settings` file. Does that include paths with folds?

**Comment by 64kramsystem** [comment]
OK, closing the issue, because it's actually this:

> When you start Sublime Text for the first time, it opens the last files you have been working with, unfortunately the plugin won't restore the folded regions because there isn't any event for that yet. However, closing and reopening the files (or project) fixes this issue.

I've been using it for a while, but I changed my workflow recently, so that the new workflow triggers the issue, but the previous one didn't.

I'm not sure about the filename :smile: It may be that I was using an old version, and trying to figure out the problem, I've updated the version, which has a different path - but this is a supposition, and my reference to this is essentially irrelevant :smile: 

Thanks and sorry!

**Comment by acheronfail** [comment]
@saveriomiroddi FWIW restoring folds at startup was implemented in d5ee3e9f.

**Comment by 64kramsystem** [comment]
Wow, just noticed that. Thanks! :+1:

**Comment by ghost** [comment]
in my case. I had installed **jshint** and **csslint**. These packages were unfolding all the folding which I had folded before. If you don't need these packages then just remove them and you are good to go.
